Se cambia el orden de los steps del action

diff --git a/.github/actions/test/nodejs/action.yml b/.github/actions/test/nodejs/action.yml
--- a/.github/actions/test/nodejs/action.yml
+++ b/.github/actions/test/nodejs/action.yml
@@ -3,20 +3,6 @@ description: Acción para ejecutar pruebas de una aplicación Node.js
 runs:
   using: "composite"
   steps:
-    - name: Instalar dependencias
-      shell: powershell
-      working-directory: ./app
-      run: |
-        echo "Instalando dependencias..."
-        npm install
-        if ($LASTEXITCODE -ne 0) {
-          Write-Error "Error al instalar dependencias"
-          exit 1
-        }
-        else {
-          Write-Host "Dependencias instaladas correctamente"
-        }
-
     - name: Buscamos el directorio de la aplicación
       id: find_project_directory
       shell: powershell
@@ -45,6 +31,20 @@ runs:
         if (-not $packageJson.scripts.test) {
           Write-Error "No se encontró el script de pruebas en package.json"
           exit 1
+        }
+
+    - name: Instalar dependencias
+      shell: powershell
+      working-directory: ${{ steps.find_project_directory.outputs.project_directory }}
+      run: |
+        echo "Instalando dependencias..."
+        npm install
+        if ($LASTEXITCODE -ne 0) {
+          Write-Error "Error al instalar dependencias"
+          exit 1
+        }
+        else {
+          Write-Host "Dependencias instaladas correctamente"
         }
 
     - name: Ejecutamos las pruebas
